# Generated by Django 4.2.23 on 2025-11-03 23:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=250)),
                ('osm_type', models.CharField(max_length=100)),
                ('osm_id', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('place_rank', models.IntegerField()),
                ('importance', models.FloatField()),
                ('addresstype', models.CharField(max_length=100)),
                ('boundingbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
